//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Uri { get; set; }
        public string Text1 { get; set; }
        public string Text1Raw { get; set; }
        public string Text2 { get; set; }
        public string Text2Raw { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<bool> Meta { get; set; }
        public int ArticleCategoryId { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public bool RawContent { get; set; }
        public Nullable<bool> FB { get; set; }
    
        public virtual ArticleCategory ArticleCategory { get; set; }
        public virtual User User { get; set; }
    }
}
