//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int CommentedUserId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int AuthorUserId { get; set; }
        public string Body { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User AuthorUser { get; set; }
        public virtual User CommentedUser { get; set; }
    }
}
