//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int Id { get; set; }
        public Nullable<int> TargetUserId { get; set; }
        public string IP { get; set; }
        public string Host { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Type { get; set; }
    
        public virtual User AuthorUser { get; set; }
        public virtual User LikedUser { get; set; }
    }
}
