//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public string ContentType { get; set; }
        public string Description { get; set; }
        public string Guid { get; set; }
        public string Uri { get; set; }
        public bool IsActive { get; set; }
        public int Position { get; set; }
        public bool IsMain { get; set; }
    
        public virtual User User { get; set; }
    }
}
